@serviceUrl=http://localhost:5001/social-5f7d3/us-central1/api
@AuthorizationToken=Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ5YWQ5YmM1ZThlNDQ3OTNhMjEwOWI1NmUzNjFhMjNiNDE4ODA4NzUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsLTVmN2QzIiwiYXVkIjoic29jaWFsLTVmN2QzIiwiYXV0aF90aW1lIjoxNTk5OTgxNDc0LCJ1c2VyX2lkIjoiSVJVSXlxMDJBMlM1VWZpc2hiUFUzMW04VUJ3MiIsInN1YiI6IklSVUl5cTAyQTJTNVVmaXNoYlBVMzFtOFVCdzIiLCJpYXQiOjE1OTk5ODE0NzQsImV4cCI6MTU5OTk4NTA3NCwiZW1haWwiOiJ0ZXN0ZXI0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0ZXI0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.j1FTNBYaaoaJRe72ZkRAr1O5KSFC4O_EYMeDBV4MGWAGGYlZoKiIp6PSGBAXEXXcjAAu_ZwlQMIKFFHqF_Ucb2yfkf6zdbCERG6wL7NfbPFZ8hFocHpIVSMI8zT37tYvXCyabEkBCxp7gQ39CQ4DWbvAkJ6Uvo6abSjnW-LhS61zh3fA4e_CKEbiOyQoiiBLHqJiAnsMcHTG3aL0neunR44FBIFIJD2BwhJW2G6B3iA8TgsMmyyYHjK2hlkv9bkmP1QAljMUGpsZLyw2kHzZEpDqYYX859n5ZgyQge7ZSC-aLlBzkED6qEAk3Z_uFNl2piBy6255rOWcUfsfJOubJg
@screamId=5bU4gvT79F2huRoWnqX3
### Get all the screams
GET {{serviceUrl}}/screams

### Get scream
GET {{serviceUrl}}/scream/{{screamId}}

### Post scream
POST {{serviceUrl}}/scream
Content-Type: application/json
Authorization: {{AuthorizationToken}}
 
{
    "body": "Hello hello from tester3"
}

### Delete scream
DELETE {{serviceUrl}}/scream/{{screamId}}
Authorization: {{AuthorizationToken}}


### Comment on scream
POST {{serviceUrl}}/scream/{{screamId}}/comment
Content-Type: application/json
Authorization: {{AuthorizationToken}}

{
    "body": "Comment from tester4"
}

### Like scream
GET {{serviceUrl}}/scream/{{screamId}}/like
Authorization: {{AuthorizationToken}}


### Unlike scream
GET {{serviceUrl}}/scream/{{screamId}}/unlike
Authorization: {{AuthorizationToken}}

### sign up
POST {{serviceUrl}}/signup
Content-Type: application/json

{
    "email": "tester4@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "handle": "tester4"
}

### login
POST {{serviceUrl}}/login
Content-Type: application/json

{
    "email": "tester4@gmail.com",
    "password": "123456"
}

### add user details
POST {{serviceUrl}}/user
Content-Type: application/json
Authorization: {{AuthorizationToken}}

{
    "bio": "Hello, I'm user",
    "website": "www.facebook.com",
    "location": "Los Angeles"
}

### get user details 
GET {{serviceUrl}}/user/tester3

### get user credentials
GET {{serviceUrl}}/user
Content-Type: application/json
Authorization: {{AuthorizationToken}}          

### Mark notification as read
POST {{serviceUrl}}/notifications
Content-Type: application/json
Authorization: {{AuthorizationToken}}

[
    "XajA0VeuLi3kKmP1OqEz",
    "c0G2SKupbQRorwRGSwBE"
]