@serviceUrl=http://localhost:5000/social-5f7d3/us-central1/api
@AuthorizationToken=Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ5YWQ5YmM1ZThlNDQ3OTNhMjEwOWI1NmUzNjFhMjNiNDE4ODA4NzUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsLTVmN2QzIiwiYXVkIjoic29jaWFsLTVmN2QzIiwiYXV0aF90aW1lIjoxNTk5MzgyMzgxLCJ1c2VyX2lkIjoiQlJWQXJRdjJkb2dNR0loZWxLV0VxeVlJRnlRMiIsInN1YiI6IkJSVkFyUXYyZG9nTUdJaGVsS1dFcXlZSUZ5UTIiLCJpYXQiOjE1OTkzODIzODEsImV4cCI6MTU5OTM4NTk4MSwiZW1haWwiOiJ0ZXN0ZXIyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0ZXIyQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.AI2gAhNwfNaHFeWM6Cz7JDd6UVwXGksC1OvP-Okj5I9883RNVdILpV_yQ5_vkzwa-JVPQXl6JT-XSyDN1SiO_pNJfPcju3Thf70oTrueDml_8uXkZXIWZXythsCQDtturE1P8B-0mmOhI57aaZPD1RS0D9HxU9-dhpZNkOr_Xi0U_psyNE6_y6mZupGXyXN9HuZpRnCDdEf7FDA1bVS8SmMXwVNgO6fcw8N5KF-TjBSqXwBkHG9MPqeWJLIyw4SRmffJzgGP4i6zSSQ931HxIpmQLx1h3phnzPd95FWfeZSgg-iXdGLTS_uiSfAnci-Est0ruPzb-Fi-FzAwTiM2_A
@screamId=5bU4gvT79F2huRoWnqX3

### Get all the screams
GET {{serviceUrl}}/screams

### Get scream
GET {{serviceUrl}}/scream/{{screamId}}

### Post scream
POST {{serviceUrl}}/scream
Content-Type: application/json
Authorization: {{AuthorizationToken}}

{
    "body": "pool",
    "userHandle": "Joke"
}

### Comment on scream
POST {{serviceUrl}}/scream/{{screamId}}/comment
Content-Type: application/json
Authorization: {{AuthorizationToken}}

{
    "body": "Comment 3"
}

### sign up
POST {{serviceUrl}}/signup
Content-Type: application/json

{
    "email": "tester2@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "handle": "user13"
}

### login
POST {{serviceUrl}}/login
Content-Type: application/json

{
    "email": "tester2@gmail.com",
    "password": "123456"
}

### add user details
POST {{serviceUrl}}/user
Content-Type: application/json
Authorization: {{AuthorizationToken}}

{
    "bio": "Hello, I'm user",
    "website": "www.facebook.com",
    "location": "Los Angeles"
}

### get user credentials
GET {{serviceUrl}}/user
Content-Type: application/json
Authorization: {{AuthorizationToken}}